- src/styles/colors.js
- src/styles/global.js
- src/styles/index.js
- src/styles/reset.js
- src/styles/typography.js
added colors, typography, reset, and global
> chore: add styles

- package-lock.json
- package.json
- src/App.jsx
- src/components/buttons/Button.jsx
- src/styles/colors.js
> chore: add buttons component

- src/components/inputs/Input.jsx
- src/components/inputs/inputSearch.jsx
> add: input and input search

- src/pages/LandingPage.jsx
finished landing page view details with header and footer.
> feat: update landing page

- src/App.jsx
- src/components/Wrapper.jsx
- src/components/inputs/Input.jsx
- src/pages/ProfessionalProfilePage.jsx
- src/styles/typography.js
added professional profile page, details pending.
> feat: add professional profile page

- src/App.jsx
- src/components/Wrapper.jsx
- src/components/inputs/input-price.jsx
- src/components/inputs/inputSelect.jsx
fixed styles of select input and find job page
> fix: select input

- src/App.jsx
- src/components/Wrapper.jsx
- src/components/inputs/Input-textarea.jsx
- src/pages/ProfessionalProfilePage.jsx
Update Professional Profile Page and added input textarea component
> chore: update professional profile page

- src/pages/FollowingPage.jsx
- src/pages/SearchPage.jsx
> add: followings page!

- src/App.jsx
- src/components/Wrapper.jsx
- src/components/inputs/Input-textarea.jsx
- src/components/inputs/Input.jsx
- src/components/inputs/input-price.jsx
- src/components/inputs/inputSelect.jsx
- src/pages/NewJobPage.jsx
- src/pages/RecruiterProfilePage.jsx
created new job posting page and updated input styles
> feat: add new job posting page, update input style

- src/components/CompanyFollowed.jsx
- src/pages/FollowingPage.jsx
Create a desktop 6 where you can see the company name and their jobs
> add: followed company and jobs pending

- src/components/CardJob.jsx
- src/components/Cards/ApplicationJobCard.jsx
- src/components/Wrapper.jsx
- src/components/utils.js
- src/pages/SearchPage.jsx
- src/pages/YourApplicationPage.jsx
> add: your profile

- src/components/inputs/circularCheckbox.css
- src/components/inputs/circularCheckbox.jsx
- src/components/inputs/squaredCheckbox.css
- src/components/inputs/squaredCheckbox.jsx
- src/components/inputs/tag.jsx
> checkbox y label

- package-lock.json
- package.json
- src/components/inputs/CheckSelect.jsx
- src/components/inputs/checkselect.css
> add: select input from react

- package-lock.json
- package.json
- src/App.jsx
- src/config.js
- src/main.jsx
- src/pages/LoginPage.jsx
- src/pages/MainPage.jsx
- src/services/api-fecth.js
- src/services/professional-services.js
> add: profesional services

- src/Authenticated.jsx
- src/components/CardJob.jsx
- src/components/RecruiterWrapper.jsx
- src/components/SidebarRecruiter.jsx
- src/components/Wrapper.jsx
- src/components/jobPosting/showJobPosting.jsx
- src/pages/ProfessionalProfilePage.jsx
- src/pages/SearchPage.jsx
- src/services/jobs-pro-services.js
> add: routing pages

- src/pages/ProfessionalProfilePage.jsx
- src/services/professional-services.js
created professional update connection with api
> chore: add update professional profile conection

- src/pages/RecruiterProfilePage.jsx
- src/services/recruiter-session.js
> recruiter-profile

- src/components/CardJob.jsx
- src/components/Wrapper.jsx
- src/components/jobDetails/JobDetails.jsx
- src/pages/NewApplication.jsx
- src/services/jobs-pro-services.js
> add: jon detail

- src/components/ProfessionalForm.jsx
- src/services/professional-services.js
- src/services/user-service.js
added create user function for professionals
> chore: add signup function to professionals

- src/components/ProfessionalForm.jsx
- src/components/RecruiterForm.jsx
- src/context/auth-context.jsx
- src/pages/RecruiterProfilePage.jsx
- src/services/recruiter-service.js
create recruiters signup functionality
> chore: add recuiters signup function

- src/components/ProfessionalForm.jsx
- src/components/RecruiterForm.jsx
- src/pages/LandingPage.jsx
created recruiter signup function for optional information and the functionality of the landing page button
> feat: add recruiter sing up function

- src/components/inputs/inputSelect.jsx
- src/pages/NewJobPage.jsx
> newjobpostin

- src/pages/NewJobPage.jsx
> fix: select input to create job

- src/components/inputs/input-price.jsx
- src/pages/NewJobPage.jsx
> fix: salary input
